### ISSUE TITLE
Mod not working for me?

### ISSUE THREAD

**Issue by Minenash** [Scotsguy/now-playing#1]
So what I did was create a new instance in multimc, installed the latest version of fabricloader, fabricapi, modmenu, and now-playing, and started it up. No settings were changed, and music played, but no popup ever showed up, and there's no errors/info related to the mod in the log.

Linux *pc-name* 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

Edit: Apparently you need the subtitles to be on for it to work.

The SuntitlesHud listner is only registered while subtitles are on, and therefor SubtitlesHud's onSoundPlayed  isn't ran

**Comment by Scotsguy** [comment]
I fixed this locally by registering a custom SoundInstanceListener, will be fixed in v1.1.0
