### ISSUE TITLE
Now Playing toast does not show when music is not in the "minecraft" namespace 

### ISSUE THREAD

**Issue by SusStew** [Scotsguy/now-playing#10]
In this [resource pack](https://github.com/Scotsguy/now-playing/files/7148344/now.playing.test.zip), the music will play but will not show the name of the song. The music is in the "bgm" namespace.

In this [resource pack](https://github.com/Scotsguy/now-playing/files/7148347/now.playing.test.2.zip), the music will play but will not show the name of the song. The music is in the "minecraft" namespace.

This would probably also affect content mods which add music.

**Comment by SusStew** [comment]
This is on the fabric version of the mod.

**Comment by JayJay1989** [comment]
To be able to show the the current track of those packs, you need to add it in the language.
like this: [language file](https://github.com/Scotsguy/now-playing/blob/master/src/main/resources/assets/now_playing/lang/en_us.json)

**Comment by SusStew** [comment]
> To be able to show the the current track of those packs, you need to add it in the language.
> like this: [language file](https://github.com/Scotsguy/now-playing/blob/master/src/main/resources/assets/now_playing/lang/en_us.json)

That only works when it's set to minecraft:music/path/to/file. When it is set to any namespace other than minecraft, e.g. bgm:music/path/to/file, it doesn't work.

**Comment by JayJay1989** [comment]
hmm, i will fix this when i have some spare time

**Comment by Scotsguy** [comment]
This works now, and will be in the v1.4.0 release of the mod. I'll see about releasing that soon.

![image](https://user-images.githubusercontent.com/20385973/148698505-3884391e-800f-4c81-88e0-4351cd40daf8.png)
