### ISSUE TITLE
[Feature Request] Option to disable the toast "whoosh" sound

### ISSUE THREAD

**Issue by SaphireLattice** [Scotsguy/now-playing#15]
I quite like the visual style of it, but the whoosh is a bit distracting from the song as it starts playing. It would be really nice to have a way to disable the sound of it appearing and disappearing?

**Comment by Scotsguy** [comment]
I've programmed this and it works, I'll see about getting a release out soon. Good idea!

**Comment by Scotsguy** [comment]
This is now released in v1.3.0 on Fabric.
