### ISSUE TITLE
1.19 Support?

### ISSUE THREAD

**Issue by TheRealCyber** [Scotsguy/now-playing#16]
Is there any ETA to when the mod will update to 1.19 to support the new disc?
I use Fabric

**Comment by Scotsguy** [comment]
I'm currently a bit busy, but I'll see if I can't update it within the next week or two. Alternatively, PRs are welcome.

**Comment by JayJay1989** [comment]
~~Will do it this weekend, nw~~

edit: ported it to 1.19 already, also included quilt: [dev/1.19.x](https://github.com/Scotsguy/now-playing/tree/dev/1.19.x)
