### ISSUE TITLE
Error in Launch 

### ISSUE THREAD

**Issue by skateboardsnail** [Scotsguy/now-playing#19]
I downloaded the file called v1.4.2 for 1.19 and i couldn't get past the launcher after i added it to my mods folder and restarted. the error code is as follows 

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

the exit code is -1 

thanks

**Comment by Scotsguy** [comment]
Do you use OptiFine? If so, Now Playing is incompatible with it, you'll have to remove one of the two. If you don't, please upload the full log.

**Comment by skateboardsnail** [comment]
optifine is active, I mustve missed that in the description
