### ISSUE TITLE
Crash initialy.

### ISSUE THREAD

**Issue by Taknax** [Scotsguy/now-playing#20]
I want to use this beautiful mod in my modpack, but i occure a crash by launching MC.
I use MC 1.19.2 with Forge 43.1.65. Mod version is 1.4.2.
I dont use optifine, so it is not optifine related issue.
Here is the crashlog:
[https://pastebin.com/P3h98mP6](https://pastebin.com/P3h98mP6)

**Comment by NotRyken** [comment]
Closing this as versions prior to mc1.21 are no longer supported. 
Please open a new issue if the problem persists on latest release.
