### ISSUE TITLE
Pop-up spam when volume is set to 0 & MoreMusic is installed

### ISSUE THREAD

**Issue by tesseract-two** [Scotsguy/now-playing#22]
Notifications continue to pop up when volume is set to zero. This gets bad with [More Music](https://modrinth.com/mod/moremusic) or similar, as it repeatedly shows music pop-ups. Maybe you could disable the toasts when the Master or Music volume sliders are set to zero?

**Comment by Scotsguy** [comment]
Normally, Minecraft completely disables the sound system when the volume is set to 0 (you can test this for yourself by turning the volume to 0 partway through a song, and then back up again - it will stop playing).

What version of Minecraft does this happen on, and with what other mods + what versions of those mods? that'll help me figure out what is causing this.

(also see: https://github.com/juliand665/Dynamic-FPS/pull/56)

**Comment by tesseract-two** [comment]
I'm sorry I'm responding so late, I forgot about this... anyway I was able to reproduce this with 
> Minecraft 1.19.2
Lithium - 0.11.1
Sodium - 0.4.4+build.18
Starlight - 1.1.1+fabric.ae22326
No Telemetry - 1.7.0
Mod Menu - 4.2.0-beta.2
Now Playing - 1.4.2

Oddly, I haven't seen this happen when the Music volume slider is set to 0, only when the Master slider is set to 0 (and the Music slider is not set to 0). Do you by chance check if the Music volume is set to 0 and disable, but not check the Master volume? This issue isn't terrible with vanilla playback rules -the most pop-ups I've seen at once is two- but they are frequent, and probably shouldn't be showing because as you said, the vanilla music system should be disabled. Setting the music cooldown low with More Music perpetually covers the top left corner of the screen though.

Thanks for your time (and patience)!
