### ISSUE TITLE
[Feature Request] Add keybind to display current song

### ISSUE THREAD

**Issue by BigMartin58** [Scotsguy/now-playing#23]
I think it would be a really good addition to include a keybind which, when pressed, will display the current song in the same way as when it first starts playing because sometimes I miss the notification and would like to see it again.

That is all. Thank you for the mod! :D

**Comment by AyOhEe** [comment]
Bump. This is mostly why I installed the mod. I would hear a song in game and then want to listen to it outside of the game. Not being able to do this without being hypervigilant about the notification isn't really a solution for me.

**Comment by NotRyken** [comment]
Added in 337b8fd for release in v1.5.3, note that it is impractical to determine whether a song is *currently* playing, so the keybind simply displays the most-recently-started song.
