### ISSUE TITLE
Game crashes on version 1.19.4

### ISSUE THREAD

**Issue by Fleepe** [Scotsguy/now-playing#29]
I was doing some stuff in the game menu and apparently when the music in the menu started playing, the game crashed.
The crash.log file was not created.
[latest.log](https://github.com/Scotsguy/now-playing/files/12061325/latest.log)

**Comment by Yupoman** [comment]
Also in 1.20.1, Forge 47.1.43

**Comment by NotRyken** [comment]
Closing this as versions prior to mc1.21 are no longer supported. 
Please open a new issue if the problem persists on latest release.
