### ISSUE TITLE
music cycles all the music

### ISSUE THREAD

**Issue by Linguardium** [Scotsguy/now-playing#3]
![image](https://user-images.githubusercontent.com/61733861/89086985-78243900-d347-11ea-93ae-e2f8101618fa.png)

open options->sound->turn volume all the way down

**Comment by Linguardium** [comment]
edit: nvm, its totally muting, it just backs up a LOT so even turning sound back on takes a LONG time to stop cycling

might not be related to muting.

**Comment by Scotsguy** [comment]
Can't reproduce, turning off sound just stops the toasts from appearing (as it should)

**Comment by JayJay1989** [comment]
turning the volume all way down does indeed stop the music completely. 
Spamming volume up and all way down does this spamming because the mainmenu has always music playing.
Its not a bug, its a vanilla thing

**Comment by Linguardium** [comment]
this had nothing to do with spamming volume levels, given that this mod doesnt cause this issue, it is likely another mod that doesnt handle the volume off function well and continues to attempt to play music after one ends.

In this case, infinite music seems to have been the culprit.  Sorry for the trouble.

**Comment by Scotsguy** [comment]
Ah, that makes sense. go bug the infinite music dev that it shouldn't play when music is muted
