### ISSUE TITLE
Incompatible with Mixtape & Music Control

### ISSUE THREAD

**Issue by piebaker** [Scotsguy/now-playing#30]
Crashes with Mixtape or music control installed
https://modrinth.com/mod/mixtape
https://modrinth.com/mod/music-control
https://mclo.gs/NDNkiJE

**Comment by piebaker** [comment]
Turns out to be an issue with a number of separate mods, just user error

**Comment by JoeJoeTV** [comment]
@piebaker Do you know the mods that caused the problems you were having?
