### ISSUE TITLE
Infinite toast whit Infinite Music

### ISSUE THREAD

**Issue by Yupoman** [Scotsguy/now-playing#31]
Similar to [https://github.com/Scotsguy/now-playing/issues/3](url) but this bug appears always with Infinite Music, muted or not.

I don't know which mod is responsible but I just want to clarify.

Minecraft 1.19.2
Forge 43.2.21
Now Playing 1.4.2
Infinite Music 1.6.0 [https://www.curseforge.com/minecraft/mc-mods/infinite-music](url)

**Comment by Yupoman** [comment]
I went in and out of my world and it sorted itself out, it's very strange. I guess the first time she did a recce or something, I have no idea.

**Comment by NotRyken** [comment]
Closing this as versions prior to mc1.21 are no longer supported. 
Please open a new issue if the problem persists on latest release.
