### ISSUE TITLE
3 Requests: Add Twilight Forest Mod support, config Keyword info, Display time?

### ISSUE THREAD

**Issue by xFirefalconx** [Scotsguy/now-playing#32]
Hi, I've tested this mod on my 1.18.2 Forge Modpack. 
1. A thing I am a tad sad about is that the Twilight Forest Mod plays a ton of cool music but I cannot see it with this mod :( Is there a way to add support? 

2. Also, I'd love a guide for the config file, for example what keywords I can insert in the config that are valid. Or a comment saying "valid parameters are: ..." on each input. 

3. Is it possible to add a configurable delay to the toast so one can add a custom timeframe the info is shown (or hotbar too, either one)? 

Great mod so far, I am really happy to at least hear the vanilla songs and know their name now!

**Comment by NotRyken** [comment]
2 is no longer relevant, editing the config file directly is unsupported. 
3 is supported as of 2ab4e50, to be released in v1.5.3

**Comment by NotRyken** [comment]
Closing as old versions are no longer supported, if you are still interested in point 1 please open a new issue when Twilight Forest is updated to latest Minecraft.
