### ISSUE TITLE
Crash on Fabric 1.20.1 for 1.4.4

### ISSUE THREAD

**Issue by Dantevg** [Scotsguy/now-playing#34]
The game crashes at the main menu in 1.20.1 (because music starts playing instantly). Version 1.4.3 worked fine, as does 1.4.4 on 1.20.2.

Mods:
- Fabric API 0.90.0+1.20.1
- Now Playing 1.4.4 

[crash-2023-10-13_19.20.38-client.txt](https://github.com/Scotsguy/now-playing/files/12896457/crash-2023-10-13_19.20.38-client.txt)

**Comment by Scotsguy** [comment]
Sorry, looks like I mistagged that version. Use 1.4.3 for 1.20.1 and 1.4.4 for 1.20.2.
