### ISSUE TITLE
Spams Music Toasts When Used With Ad Astra

### ISSUE THREAD

**Issue by LThreeZeroT** [Scotsguy/now-playing#36]
Whenever I go up into space to a space station, the music toasts are spammed constantly in the corner of my screen.

**Comment by NotRyken** [comment]
This will be addressed when Ad Astra is available for latest Minecraft, if it can be reproduced.

**Comment by NotRyken** [comment]
Closing this out as there isn't an ETA for Ad Astra 1.21, please open a new issue when/if Ad Astra supports latest and the problem still exists.
