### ISSUE TITLE
Feature Request: Add Compatibility To Nature's Melody

### ISSUE THREAD

**Issue by LThreeZeroT** [Scotsguy/now-playing#37]
Nature's Melody has very good music, and it would awesome if I could see what the name of the song actually playing was.

**Comment by NotRyken** [comment]
Closing this as Nature's Melody is not being actively maintained and old versions of Now Playing are no longer supported. Please open a new issue when/if Nature's Melody is updated and you are still interested in seeing compatibility.

**Comment by NotRyken** [comment]
Update since Nature's Melody is now on latest, Nature's Spirit handles music differently to vanilla Minecraft so while compatibility at some point isn't entirely out of the question, it isn't likely to happen soon (and not before Nature's Melody is made open-source).
