### ISSUE TITLE
[1.21] New Music

### ISSUE THREAD

**Issue by Scotsguy** [Scotsguy/now-playing#40]
From the changelog:

Music

Added 9 new background music tracks which will all play in the main menu:

    "Featherfall" by Aaron Cherof
        Plays in Badlands, Cherry Grove, Flower Forest, and Lush Caves Biomes
    "Deeper" by Lena Raine
        Plays in Deep Dark and Dripstone Caves Biomes
    "Eld Unknown" by Lena Raine
        Plays in Dripstone Caves, Grove, Jagged Peaks, and Stony Peaks Biomes
    "Endless" by Lena Raine
        Plays in Dripstone Caves, Grove, Jagged Peaks, and Stony Peaks Biomes
    "pokopoko" by Kumi Tanioka
        Plays in Dripstone Caves, Grove, Jagged Peaks, and Snow Slopes Biomes

The following have been added to the pool of songs which play in Overworld Biomes that do not have biome-specific music:

    "Featherfall" by Aaron Cherof
    "komorebi" by Kumi Tanioka
    "Puzzlebox" by Aaron Cherof
    "Watcher" by Aaron Cherof
    "yakusoku" by Kumi Tanioka

**Comment by NotRyken** [comment]
Turns out the wiki source that I used in the 1.20.4 update had the 1.21 music, so they were already there. There is the question of capitalization though, I converted them to title case for consistency but they might be intentionally lowercase.

**Comment by Scotsguy** [comment]
I'd leave them with the official capitalization, they're lowercase everywhere else too (spotify, soundcloud...)

**Comment by NotRyken** [comment]
Fixed in 3231767
