### ISSUE TITLE
Setting "Jukebox pop-up style" doesn't work

### ISSUE THREAD

**Issue by Salubra** [Scotsguy/now-playing#42]
### Mod Version

v1.5.4-Fabric-1.21

### Mod Loader

Fabric

### Minecraft Version

1.21

### Bug Description

When "Jukebox pop-up style" is set to Hotbar, when playing music using jukebox, the toast appears. But if you change "Music pop-up style" to Hotbar, default music and jukebox music will be displayed on hotbar

### Reproduction Steps

1. Set "Music pop-up style" to Toast
2. Set "Jukebox pop-up style" to Hotbar
3. Play music in jukebox

**Comment by NotRyken** [comment]
Confirmed, thanks for reporting. Not sure how I missed it in testing but it's a simple fix, will get it done later today.
