### ISSUE TITLE
Custom Music Not Showing Properly

### ISSUE THREAD

**Issue by LagoRoxo** [Scotsguy/now-playing#5]
![unknown](https://user-images.githubusercontent.com/53158475/91907920-1c6c0900-ec81-11ea-95d3-8a3ae6986915.png)
Playing custom music added by resource packs appears as in the image(either toast or hotbar)

![image](https://user-images.githubusercontent.com/53158475/91908328-c0ee4b00-ec81-11ea-9f69-f5555438faf8.png)

Here's a resource pack to test it by yourself:
[to_github.zip](https://github.com/Scotsguy/now-playing/files/5159009/to_github.zip)
(the zip contains a readme with a step-by-step tutorial to reproduce the bug)

**game version**: 1.16.2
**mod version**: v1.1.4-forge

**Comment by JayJay1989** [comment]
I will look into it

**Comment by Scotsguy** [comment]
This is a problem that isn't fixable easily - sounds.json doesn't include a human-readable name, so what should this display? Probably nothing, to be fair.
This is, however, manually fixable (in theory): create a file in assets/now_playing/lang/en_us.json and add a language file entry for "now_playing.sound.music/game/nether/soulsand_valley/testing" with whatever you want your song to be called. Basically, do it like this: https://github.com/Scotsguy/now-playing/blob/master/src/main/resources/assets/now_playing/lang/en_us.json

**Comment by Scotsguy** [comment]
![image](https://user-images.githubusercontent.com/20385973/92001694-484dc400-ed3f-11ea-8d80-cdd7ae168619.png)
Sure enough, this works.
Example zip:
[now_playing_custom_music.zip](https://github.com/Scotsguy/now-playing/files/5163164/now_playing_custom_music.zip)
Still gotta make a bit of a nicer error message, though

**Comment by LagoRoxo** [comment]
my suggestion is to add a config file where the user could do this easily.
maybe like a JSON table like this:
[{
"path" : "",
"author": "",
"name":""
}]
and then make a script to add it, but I don't know how flexible Fabric or Forge is but thank you.

**Comment by Scotsguy** [comment]
Closing to clean up the issue tracker, songs that don't have names won't be displayed at all anymore.
