### ISSUE TITLE
Forge branch fails to run in dev environment

### ISSUE THREAD

**Issue by PaintNinja** [Scotsguy/now-playing#6]
Error: `java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry`

Steps to reproduce:
1. Clone the forge branch of this repo
2. Import the clone into IntelliJ
3. Run `gradlew runClient`

Crash report: https://pastebin.com/raw/7fvsLtJN

**Comment by JayJay1989** [comment]
Thats right, mixin doesn't work within runtime. At least you need the [Mixin Bootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) mod

**Comment by PaintNinja** [comment]
You don't need Mixin Bootstrap as of a while now, it's been available in Forge since 1.16.1-32.0.72+ according to the mod's own description.

I tried downloading the Mixin Bootstrap mod and putting it in the run\mods folder anyway and the same crash happens.

**Comment by JayJay1989** [comment]
its a mixin problem, ask on the forge discord in the channel 'non-api-modding' channel

**Comment by PaintNinja** [comment]
Can you confirm whether or not you can execute `gradlew runClient` successfully on your end with a clone of the Forge branch of this repo?

**Comment by JayJay1989** [comment]
its not possible to run mixins from a workspace.

**Comment by PaintNinja** [comment]
Alright, built a jar and tested it on a production env and it works. Building it with `gradlew jar` didn't work however building it with `gradlew reobfJar` did.
