### ISSUE TITLE
[Bug?] Repeated toast dialogs

### ISSUE THREAD

**Issue by EvieTheOwl** [Scotsguy/now-playing#8]
Found this happen when testing. Player was spammed with end boss music notifications upon joining the end for the first time. Haven't been able to reproduce since.

**Version**: Running version 1.1.4

**Video link**: https://streamable.com/ygjo9q

**Comment by JayJay1989** [comment]
is this forge or fabric?

**Comment by Scotsguy** [comment]
Can't repro just with now playing
can't repro in the ttt creative pack in singleplayer nor on a dedicated server

**Comment by EvieTheOwl** [comment]
> is this forge or fabric?

Fabric

**Comment by Scotsguy** [comment]
i randomly happened upon this issue again. It's because of dynamic FPS
Closing in favour of https://github.com/juliand665/Dynamic-FPS/issues/55
